# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andy Makovec
email: andymakovec@gmail.com
description: >
  Hardware Engineer in Cleveland, OH
logo: "/assets/images/logo.jpg"
baseurl: ""                             # the subpath of your site, e.g. /blog
url: "http://amakovec.com"              # the base hostname & protocol for your site
paginate: 5                             # The number of posts to show per page on your homepage

# Bio settings
name: 'Andy Makovec'
bio: >
  Hardware Engineer in Cleveland, OH
author_image: "/assets/images/author.jpg"
twitter_username: andymakovec
github_username:  amakovec

# Google Analytics
analytics_id: "UA-127706275-1"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
